---
title: "Project LSTAT2130"
author: "Mathieu"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = FALSE,
  warning = FALSE
)
```

```{r}
library(tidyverse)
library(knitr)
library(kableExtra)

library(rjags)
library(R2jags)
library(R2WinBUGS)
library(bayesplot)
library(bayestestR)
library(shinystan)
library(bit64)

library(stats)
library(coda)
library(mvtnorm)

library(patchwork)
library(latex2exp)
library(progress)
```

```{r}
set.seed(123)
rm(list = ls())
```

```{r}
# global variables 
N_STEPS <- 140000
N_BURNIN <- 5000
BURNIN <- c(1:N_BURNIN)
```

```{r}
df <- read.table("dataset/TumorGrowth.txt")
head(df)
```

```{r}
# formulas linking alpha_k and beta_k
alpha <- function(theta) {
  exp(theta)
}

beta <- function(alpha) {
  beta <- numeric(length(alpha))
  
  beta[1] <- alpha[1] / exp(alpha[2])
  beta[2] <- alpha[2] * alpha[3]
  beta[3] <- alpha[3]
  
  return(beta)
}
```

# 2.b

R function to compute the log-likelihood $L(\vec{\alpha}|\mathcal{D}_i)$ given parameter values $\theta_k = \log(\theta_k)$ and data $D_i$
```{r}
mu <- function(alpha, t_j) {
  alpha[1] * exp(- alpha[2] * exp(- alpha[3] * t_j))
}

log.mu <- function(alpha, t_j) {
  log(alpha[1]) - alpha[2] * exp(- alpha[3] * t_j)
}

log.likelihood <- function(theta, t, experiment) {
  n <- length(t)
  alpha <- exp(theta)
  
  result <- sum(sapply(1:n, function(j) {
    dpois(x = t[j], lambda = exp(log.mu(alpha, t[j])), log = TRUE)
  }))
  
  return(result)
}
```

# 2.c

```{r}
log.prior <- function(theta) {
  theta0 <- theta[1]
  theta1 <- theta[2]
  theta2 <- theta[3]
  
  prior.theta0 <- dnorm(theta0, mean = 0, sd = 10, log = TRUE)
  prior.theta1 <- dnorm(theta1, mean = 0, sd = 10, log = TRUE)
  prior.theta2 <- dnorm(theta2, mean = 0, sd = 10, log = TRUE)
  
  return(prior.theta0 + prior.theta1 + prior.theta2)
}

log.posterior <- function(theta, t, experiment) {
  log.likelihood(theta, t, experiment) + log.prior(theta)
} 
```

# 2.d

```{r}
laplace.approximation <- function(log.posterior, inits, n_samples, ...) {
  fit <- optim(
    par = inits,
    fn = log.posterior,
    control = list(fnscale = -1),
    hessian = TRUE,
    ...
  )
  
  print(fit$hessian)
  
  mean <- fit$par
  var_cov_matrix <- solve(-fit$hessian)
  samples <- rmvnorm(20000, mean, var_cov_matrix)
  
  return(list(
    mean = mean,
    var_cov_matrix = var_cov_matrix,
    samples = samples
  ))
}

inits <- c(theta0 = 0.25, theta1 = 0.25, theta2 = 0.25)
lapprox <- laplace.approximation(log.posterior, inits, 50000, t = df$day, experiment = df$Exp1)
```

```{r}
lapprox$mean
lapprox$var_cov_matrix
```

```{r}
lapprox.samples <- data.frame(mcmc(lapprox$samples))

p1 <- ggplot(lapprox.samples, aes(x = theta0)) +
  geom_histogram(aes(y = ..density..), color = "black", fill = "white") +
  geom_density(color = "seagreen", size = 1)

p2 <- ggplot(lapprox.samples, aes(x = theta1)) +
  geom_histogram(aes(y = ..density..), color = "black", fill = "white") +
  geom_density(color = "seagreen", size = 1)

p3 <- ggplot(lapprox.samples, aes(x = theta2)) +
  geom_histogram(aes(y = ..density..), color = "black", fill = "white") +
  geom_density(color = "seagreen", size = 1)

p1 + p2 + p3 + plot_layout(ncol = 2)
```

## 3.a

```{r}
# Thanks to https://link.springer.com/article/10.1007/BF02789703 
metropolis.cw <- function(theta.init, sd.proposals, t, experiment, n_steps) {
  pb <- progress_bar$new(
    format = "metropolis algorithm [:bar] :percent eta: :eta",
    total = n_steps,
    clear = FALSE,
    width = 60
  )
  
  n_parameters <- length(theta.init)
  
  # matrix of dim (n_steps, n_parameters)
  theta <- matrix(nrow = n_steps, ncol = n_parameters)
  colnames(theta) <- c("theta0", "theta1", "theta2")
  
  # initialize
  theta[1, ] <- theta.init
  
  # counter
  n_accept <- rep(0, n_parameters)
  
  pb$tick(0)
  
  for (n in 2:n_steps) {
    pb$tick()
    
    # get all the current parameters for the step n
    theta.current <- theta[n - 1, ]
    
    for (i in 1:n_parameters) {
      # sample a proposal for parameter i from a normal distribution centered at the previous parameter point with a given standard deviation
      theta.proposed_i <- theta.current[i] + rnorm(1, mean = 0, sd = sd.proposals[i])
      
      # update the current parameters vector with the proposal
      theta.proposed <- theta.current
      theta.proposed[i] <- theta.proposed_i
      
      proba <- min(
        1, 
        exp(log.posterior(theta.proposed, t, experiment) - log.posterior(theta.current, t, experiment))
      )
  
      accept <- sample(0:1, 1, prob = c(1 - proba, proba))
      
      if (accept) {
        n_accept[i] <- n_accept[i] + 1
        # update the final vector
        theta[n, i] <- theta.proposed_i
        
        # update the temporary current vector for the next iteration
        theta.current[i] <- theta.proposed_i
      } else {
        # update the final vector
        theta[n, i] <- theta.current[i]
        
        # note: the value of the temporary current vector for this parameter
        # remains the same in that case
      }
    }
  }
  
  # note: n_steps - 1 because there is theta.init "automatically accepted" 
  # (we do n_steps - 1) iterations
  accept.rate <- round(n_accept / ((n_steps - 1)), 2)
  return(list(theta = theta, accept.rate = accept.rate))
}
```

```{r}
sd.proposals <- c(0.017, 0.021, 0.019)

metropolis.cw.results <- metropolis.cw(
  #theta.init = c(5.5, 0.98, 0.01),
  theta.init = lapprox$mean,
  sd.proposals = sd.proposals,
  t = df$day,
  experiment = df$Exp1,
  n_steps = N_STEPS
)

# goal is to reach an acceptance rate of 0.4
metropolis.cw.results$accept.rate
```

```{r}
# burnin
metropolis.cw.results$theta.burnin <- metropolis.cw.results$theta[-BURNIN, ]

# mcmc
metropolis.cw.mcmc <- mcmc(metropolis.cw.results$theta.burnin)
```

```{r}
p1 <- ggplot(data.frame(metropolis.cw.mcmc), aes(x = theta0)) +
  geom_histogram(aes(y = ..density..), color = "black", fill = "white") +
  geom_density(color = "seagreen", size = 1)

p2 <- ggplot(data.frame(metropolis.cw.mcmc), aes(x = theta1)) +
  geom_histogram(aes(y = ..density..), color = "black", fill = "white") +
  geom_density(color = "seagreen", size = 1)

p3 <- ggplot(data.frame(metropolis.cw.mcmc), aes(x = theta2)) +
  geom_histogram(aes(y = ..density..), color = "black", fill = "white") +
  geom_density(color = "seagreen", size = 1)

p1 + p2 + p3 + plot_layout(ncol = 2)
```

## 2.b

### Visual analysis

```{r}
traceplot(metropolis.cw.mcmc)
```

### Gelman-Rubin statistic
```{r}
chain1.cw <- metropolis.cw(
  theta.init = lapprox$mean,
  sd.proposals = sd.proposals,
  t = df$day,
  experiment = df$Exp1,
  n_steps = N_STEPS
)

chain2.cw <- metropolis.cw(
  theta.init = lapprox$mean - 1,
  sd.proposals = sd.proposals,
  t = df$day,
  experiment = df$Exp1,
  n_steps = N_STEPS
)

chain3.cw <- metropolis.cw(
  theta.init = lapprox$mean + 1,
  sd.proposals = sd.proposals,
  t = df$day,
  experiment = df$Exp1,
  n_steps = N_STEPS
)
```

```{r}
# burnin
chain1.cw$theta.burnin <- chain1.cw$theta[-BURNIN, ]
chain2.cw$theta.burnin <- chain2.cw$theta[-BURNIN, ]
chain3.cw$theta.burnin <- chain3.cw$theta[-BURNIN, ]
```


```{r}
chain.cw.list <- list(
  mcmc(chain1.cw$theta.burnin), 
  mcmc(chain2.cw$theta.burnin),
  mcmc(chain3.cw$theta.burnin)
)

traceplot(chain.cw.list)
gelman.diag(chain.cw.list)$psrf
gelman.plot(chain.cw.list)
```

### Geweke statistic

```{r}
geweke.diag(metropolis.cw.mcmc)
geweke.plot(metropolis.cw.mcmc)
```

```{r}
# computing p-value of the z-score (to know if the two means are equal)
pnorm(-1.3259, mean = 0, sd = 1, lower.tail = FALSE)
pnorm(-0.5802, mean = 0, sd = 1, lower.tail = FALSE)
pnorm(1.1019, mean = 0, sd = 1, lower.tail = FALSE)
```

### Effective sample sizes
```{r}
effectiveSize(metropolis.cw.mcmc)
```

### 3.c

```{r}
theta.mean <- colMeans(metropolis.cw.results$theta.burnin)
alpha.mean <- exp(theta.mean)

ggplot(df) +
  geom_line(aes(x = day, y = Exp1, colour = "count data series")) +
  stat_function(aes(t = day, colour = "fitted curve"), fun = function(t) exp(log.mu(alpha.mean, t))) +
  labs(
    title = "Number of cancer cells as function of time (Experiment 1)",
    x = "Day",
    y = "Number of cancer cells"
  ) +
  theme_minimal()
```

### 3.d

```{r}
# applying transformation formulas (theta -> alpha -> beta)
metropolis.cw.results$beta.burnin <- data.frame(metropolis.cw.results$theta.burnin) %>%
  rowwise() %>%
  summarise(
    alpha0 = exp(theta0),
    alpha1 = exp(theta1), 
    alpha2 = exp(theta2)
  ) %>%
  rowwise() %>%
  summarise(
    beta0 = alpha0 / exp(alpha1),
    beta1 = alpha1 * alpha2,
    beta2 = alpha2
  )
```

```{r}
# point estimates for theta
point_estimate(as.mcmc(metropolis.cw.results$beta.burnin))
```

```{r}
# 95% credible regions
HPDinterval(as.mcmc(metropolis.cw.results$beta.burnin))

mcmc_areas(
  x = as.mcmc(metropolis.cw.results$beta.burnin), 
  prob = 0.95
) +
  labs(
    title = "Posterior distribution",
    subtitle = "Median and 95% credible region"
  )
```

```{r}
23.25 * exp(0.02 / 5.46e-3)

20.534731355 * exp(0.016038715 / 0.005075689)
26.031654809 * exp(0.019170682 / 0.005860116)
```

### 4.a

```{r}
metropolis.vw <- function(theta.init, sd.proposals, mult.factor, t, experiment, n_steps) {
  n_parameters <- length(theta.init)
  
  # matrix of dim (n_steps, n_parameters)
  theta <- matrix(nrow = n_steps, ncol = n_parameters)
  colnames(theta) <- c("theta0", "theta1", "theta2")
  
  # initialize
  theta[1, ] <- theta.init
  
  # counter
  n_accept = 0
  
  for (n in 2:n_steps) {
    theta.current <- theta[n - 1, ]
    theta.proposed <- theta.current + rnorm(n_parameters, mean = rep(0, n_parameters), sd = mult.factor * sd.proposals)
    
    proba <- min(
      1, 
      exp(log.posterior(theta.proposed, t, experiment) - log.posterior(theta.current, t, experiment))
    )

    accept <- sample(0:1, 1, prob = c(1 - proba, proba))
    
    if (accept) {
      n_accept <- n_accept + 1
      theta[n, ] <- theta.proposed 
    } else {
      theta[n, ] <- theta.current
    }
  }
  
  accept.rate <- round(n_accept / (n_steps - 1), 2)
  return(list(theta = theta, accept.rate = accept.rate))
}
```

```{r}
metropolis.vw.results <- metropolis.vw(
  theta.init = lapprox$mean,
  sd.proposals = diag(lapprox$var_cov_matrix),
  mult.factor = 20,
  t = df$day,
  experiment = df$Exp1,
  n_steps = N_STEPS
)

# we should aim for 20% of acceptance rate
metropolis.vw.results$accept.rate
```

```{r}
# burnin
metropolis.vw.results$theta.burnin <- metropolis.vw.results$theta[-BURNIN, ]

# mcmc
metropolis.vw.mcmc <- mcmc(metropolis.vw.results$theta.burnin)
```

```{r}
p1 <- ggplot(data.frame(metropolis.vw.mcmc), aes(x = theta0)) +
  geom_histogram(aes(y = ..density..), color = "black", fill = "white") +
  geom_density(color = "seagreen", size = 1)

p2 <- ggplot(data.frame(metropolis.vw.mcmc), aes(x = theta1)) +
  geom_histogram(aes(y = ..density..), color = "black", fill = "white") +
  geom_density(color = "seagreen", size = 1)

p3 <- ggplot(data.frame(metropolis.vw.mcmc), aes(x = theta2)) +
  geom_histogram(aes(y = ..density..), color = "black", fill = "white") +
  geom_density(color = "seagreen", size = 1)

p1 + p2 + p3 + plot_layout(ncol = 2)
```

### 4.b

### Visual analysis

```{r}
traceplot(metropolis.vw.mcmc)
```

### Gelman-Rubin statistic
```{r}
chain1.vw <- metropolis.vw(
  theta.init = lapprox$mean,
  sd.proposals = diag(lapprox$var_cov_matrix),
  mult.factor = 20,
  t = df$day,
  experiment = df$Exp1,
  n_steps = N_STEPS
)

chain2.vw <- metropolis.vw(
  theta.init = lapprox$mean - 1,
  sd.proposals = diag(lapprox$var_cov_matrix),
  mult.factor = 20,
  t = df$day,
  experiment = df$Exp1,
  n_steps = N_STEPS
)

chain3.vw <- metropolis.vw(
  theta.init = lapprox$mean + 1,
  sd.proposals = diag(lapprox$var_cov_matrix),
  mult.factor = 20,
  t = df$day,
  experiment = df$Exp1,
  n_steps = N_STEPS
)
```

```{r}
# burnin
chain1.vw$theta.burnin <- chain1.vw$theta[-BURNIN, ]
chain2.vw$theta.burnin <- chain2.vw$theta[-BURNIN, ]
chain3.vw$theta.burnin <- chain3.vw$theta[-BURNIN, ]
```


```{r}
chain.vw.list <- list(
  mcmc(chain1.vw$theta.burnin), 
  mcmc(chain2.vw$theta.burnin),
  mcmc(chain3.vw$theta.burnin)
)

traceplot(chain.vw.list)
gelman.diag(chain.vw.list)$psrf
gelman.plot(chain.vw.list)
```

### Geweke statistic

```{r}
# z-score
geweke.diag(metropolis.vw.mcmc)
geweke.plot(metropolis.vw.mcmc)
```
```{r}
# computing p-value of the z-score (to know if the two means are equal)
pnorm(-0.4956, mean = 0, sd = 1, lower.tail = FALSE)
pnorm(-1.7949, mean = 0, sd = 1, lower.tail = FALSE)
pnorm(-0.4138, mean = 0, sd = 1, lower.tail = FALSE)
```

### Effective sample sizes
```{r}
effectiveSize(metropolis.vw.mcmc)
```

```{r}
theta.mean <- colMeans(metropolis.vw.results$theta.burnin)
alpha.mean <- exp(theta.mean)

ggplot(df) +
  geom_line(aes(x = day, y = Exp1, colour = "count data series")) +
  stat_function(aes(t = day, colour = "fitted curve"), fun = function(t) exp(log.mu(alpha.mean, t))) +
  labs(
    title = "Number of cancer cells as function of time (Experiment 1)",
    x = "Day",
    y = "Number of cancer cells"
  ) +
  theme_minimal()
```

```{r}
# applying transformation formulas (theta -> alpha -> beta)
metropolis.vw.results$beta.burnin <- data.frame(metropolis.vw.results$theta.burnin) %>%
  rowwise() %>%
  summarise(
    alpha0 = exp(theta0),
    alpha1 = exp(theta1), 
    alpha2 = exp(theta2)
  ) %>%
  rowwise() %>%
  summarise(
    beta0 = alpha0 / exp(alpha1),
    beta1 = alpha1 * alpha2,
    beta2 = alpha2
  )
```

```{r}
point_estimate(as.mcmc(metropolis.vw.results$beta.burnin))
```

```{r}
# 95% credible regions
HPDinterval(as.mcmc(metropolis.vw.results$beta.burnin))
```

```{r}
23.24 * exp(0.02 / 5.46e-3)
23.28 * exp(0.02 / 5.46e-3)

20.3473 * exp(0.0159 / 0.0050)
26.9723 * exp(0.0191 / 0.0058)
```

### 5.a 

```{r}
# jags code
model_string <- "
  model {
    alpha0 <- exp(theta0)
    alpha1 <- exp(theta1)
    alpha2 <- exp(theta2)
  
    # likelihood
    for (i in 1:n) {
      y[i] ~ dpois(mu[i])
      log(mu[i]) <- log(alpha0) - (alpha1 * exp(- alpha2 * t[i]))
    }
    
    # Priors (non-informative, large variance)
    tau <- 1 / 10^2
    theta0 ~ dnorm(0, tau)
    theta1 ~ dnorm(0, tau)
    theta2 ~ dnorm(0, tau)
  }
"

# set-up data
model_data <- list(
  n = nrow(df), y = df$Exp1, t = df$day
)

# parameters to watch
model_parameters <- c("theta0", "theta1", "theta2")

# let's run the model
model_run <- jags(
  data = model_data,
  parameters.to.save = model_parameters,
  model.file = textConnection(model_string),
  n.chains = 3,
  n.iter = N_STEPS,
  n.burnin = N_BURNIN
)

model_run.mcmc <- as.mcmc(model_run)
```

```{r}
plot(model_run)
```

```{r}
print(model_run)
```

```{r}
traceplot(model_run)
```

```{r}
gelman.diag(model_run.mcmc)$psrf
gelman.plot(model_run.mcmc)
```
### Effective sample size
```{r}
effectiveSize(model_run.mcmc)
```

### Fitted curve
```{r}
posterior <- print(model_run)

theta0.mean <- posterior$mean$theta0
theta1.mean <- posterior$mean$theta1
theta2.mean <- posterior$mean$theta2

theta.mean <- c(theta0.mean, theta1.mean, theta2.mean)
alpha.mean <- exp(theta.mean)

ggplot(df) +
  geom_line(aes(x = day, y = Exp1, colour = "count data series")) +
  stat_function(aes(t = day, colour = "fitted curve"), fun = function(t) exp(log.mu(alpha.mean, t))) +
  labs(
    title = "Number of cancer cells as function of time (Experiment 1)",
    x = "Day",
    y = "Number of cancer cells"
  ) +
  theme_minimal()
```

```{r}
point_estimate(model_run.mcmc)
```

```{r}
HPDinterval(model_run.mcmc)
```

### 5.b

```{r}
# sample the predictive number of cancer cells at time t = +\infty

# first, we retrieve the predictive posterior simulated using jags: p(\theta | D_1)
theta.jags_sample <- data.frame(as.matrix(model_run.mcmc))

# we know y ~ Pois(mu(t)) where mu(t) is given in term of alpha = exp(theta)
# since we're interested in the expected number of cancer cells at t = +\infty,
# we find that \mu(t) = alpha0
sample.size <- N_STEPS - N_BURNIN
alpha0 = exp(theta.jags_sample$theta0)
y.sample <- rpois(n = sample.size, lambda = alpha0)

# point estimates
y.mean <- mean(y.sample)
y.median <- median(y.sample)

y.credible_region <- quantile(y.sample, probs = c(.025, 0.975))

y.mean
y.median
y.credible_region
```
```{r}
ggplot(data.frame(x = y.sample), aes(x = x)) + 
  geom_density(fill = "lightgray", alpha = 0.5) +
  geom_vline(xintercept = y.mean, color = "blue", linetype ="dashed") +
  #geom_errorbarh(aes(y = 0, xmin = y.credible_region[1], xmax = y.credible_region[2]), height = 0.2, color = "red") +
  labs(
    title = "Predictive sample",
    subtitle = TeX("Expected number of cancer cells at t = $+\\infty$"),
    x = "Expected number of cancer cells",
    y = "Density"
  ) +
  theme_minimal()
```

# 6.a

```{r}
# jags code
model_string.hierarchical <- "
  model {
    alpha0[i] <- exp(theta0[i])
    alpha1[i] <- exp(theta1[i])
    alpha2[i] <- exp(theta2[i])
  
    # likelihood
    for (i in 1:n) {
      y[i, ] ~ dpois(mu[i])
      log(mu[i]) <- log(alpha0[i]) - (alpha1[i] * exp(- alpha2[i] * t[i]))
    }
    
    # priors slightly vary accross the experiments
    for (j in 1:m) {
      # Priors 
      theta0[i] ~ dnorm(mu0, tau0)
      theta1[i] ~ dnorm(mu1, tau1)
      theta2[i] ~ dnorm(mu2, tau2)
    }
    
    # Hyperpriors
    mu0 ~ dnorm(theta0.mean, 0.1)
    tau0 ~ dgamma(0.1, 0.1)
    
    mu0 ~ dnorm(theta1.mean, 0.1)
    tau0 ~ dgamma(0.1, 0.1)
    
    mu0 ~ dnorm(theta2.mean, 0.1)
    tau0 ~ dgamma(0.1, 0.1)
  }
"

# set-up data
model_data.hierarchical <- list(
  n = nrow(df), 
  m = ncol(df), 
  y = df %>% select(-day),
  t = df$day
)

# parameters to watch
model_parameters.hierarchical <- c("theta0", "theta1", "theta2")

# let's run the model
model_run.hierarchical <- jags(
  data = model_data,
  parameters.to.save = model_parameters,
  model.file = textConnection(model_string),
  n.chains = 3,
  n.iter = N_STEPS,
  n.burnin = N_BURNIN
)

model_run.hierarchical.mcmc <- as.mcmc(model_run.hierarchical)
```

```{r}
point_estimate(model_run.hierarchical.mcmc)
```